/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.main.eu.devity.burp.fidoiot.gui;

/**
 *
 * @author amay
 */
public class AttackTabPane extends javax.swing.JPanel {

    /**
     * Creates new form AttackTabPane
     */
    public AttackTabPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dropDownPanel = new javax.swing.JPanel();
        attackTypeList = new javax.swing.JComboBox<>();
        subAttackList = new javax.swing.JComboBox<>();
        certList = new javax.swing.JComboBox<>();
        attackTypeLabel = new javax.swing.JLabel();
        subAttackTypeLabel = new javax.swing.JLabel();
        certTypeLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        attackTypeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Signature Exclusion", "Key Confusion", "SSRF" }));
        attackTypeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackTypeListActionPerformed(evt);
            }
        });

        subAttackList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Attack" }));
        subAttackList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subAttackListActionPerformed(evt);
            }
        });

        certList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Certificate" }));

        attackTypeLabel.setText("Attack");

        subAttackTypeLabel.setText("Sub Attack");

        certTypeLabel.setText("Certificate");

        javax.swing.GroupLayout dropDownPanelLayout = new javax.swing.GroupLayout(dropDownPanel);
        dropDownPanel.setLayout(dropDownPanelLayout);
        dropDownPanelLayout.setHorizontalGroup(
            dropDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropDownPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subAttackTypeLabel)
                    .addComponent(certTypeLabel)
                    .addComponent(attackTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dropDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attackTypeList, 0, 275, Short.MAX_VALUE)
                    .addComponent(certList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subAttackList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        dropDownPanelLayout.setVerticalGroup(
            dropDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropDownPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attackTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attackTypeLabel))
                .addGap(20, 20, 20)
                .addGroup(dropDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subAttackList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subAttackTypeLabel))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(dropDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certTypeLabel))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(dropDownPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 726, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(dropDownPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 329, Short.MAX_VALUE))
        );

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyzeBtn;
    private javax.swing.JButton analyzeBtn1;
    private javax.swing.JButton analyzeBtn2;
    private javax.swing.JButton analyzeBtn3;
    private javax.swing.JButton analyzeBtn4;
    private javax.swing.JButton attackBtn;
    private javax.swing.JButton attackBtn1;
    private javax.swing.JButton attackBtn2;
    private javax.swing.JButton attackBtn3;
    private javax.swing.JButton attackBtn4;
    private javax.swing.JLabel attackTypeLabel;
    private javax.swing.JComboBox<String> attackTypeList;
    private javax.swing.JComboBox<String> certList;
    private javax.swing.JLabel certTypeLabel;
    private javax.swing.JPanel customBtnPanel;
    private javax.swing.JPanel customBtnPanel1;
    private javax.swing.JPanel customBtnPanel2;
    private javax.swing.JPanel customBtnPanel3;
    private javax.swing.JPanel customBtnPanel4;
    private javax.swing.JTextField customInput;
    private javax.swing.JTextField customInput1;
    private javax.swing.JTextField customInput2;
    private javax.swing.JTextField customInput3;
    private javax.swing.JTextField customInput4;
    private javax.swing.JPanel dropDownPanel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JLabel inputLabel1;
    private javax.swing.JLabel inputLabel2;
    private javax.swing.JLabel inputLabel3;
    private javax.swing.JLabel inputLabel4;
    private javax.swing.JScrollPane instPane;
    private javax.swing.JScrollPane instPane1;
    private javax.swing.JScrollPane instPane2;
    private javax.swing.JScrollPane instPane3;
    private javax.swing.JPanel instructionPanel;
    private javax.swing.JPanel instructionPanel1;
    private javax.swing.JPanel instructionPanel2;
    private javax.swing.JPanel instructionPanel3;
    private javax.swing.JTextPane instructionText;
    private javax.swing.JTextPane instructionText1;
    private javax.swing.JTextPane instructionText2;
    private javax.swing.JTextPane instructionText3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JButton modifyBtn1;
    private javax.swing.JButton modifyBtn2;
    private javax.swing.JButton modifyBtn3;
    private javax.swing.JButton modifyBtn4;
    private javax.swing.JCheckBox proxyCheck;
    private javax.swing.JCheckBox proxyCheck1;
    private javax.swing.JCheckBox proxyCheck2;
    private javax.swing.JCheckBox proxyCheck3;
    private javax.swing.JCheckBox proxyCheck4;
    private javax.swing.JLabel proxyHostLabel;
    private javax.swing.JLabel proxyHostLabel1;
    private javax.swing.JLabel proxyHostLabel2;
    private javax.swing.JLabel proxyHostLabel3;
    private javax.swing.JLabel proxyHostLabel4;
    private javax.swing.JTextField proxyHostText;
    private javax.swing.JTextField proxyHostText1;
    private javax.swing.JTextField proxyHostText2;
    private javax.swing.JTextField proxyHostText3;
    private javax.swing.JTextField proxyHostText4;
    private javax.swing.JLabel proxyLabel;
    private javax.swing.JLabel proxyLabel1;
    private javax.swing.JLabel proxyLabel2;
    private javax.swing.JLabel proxyLabel3;
    private javax.swing.JLabel proxyLabel4;
    private javax.swing.JLabel proxyPortLabel;
    private javax.swing.JLabel proxyPortLabel1;
    private javax.swing.JLabel proxyPortLabel2;
    private javax.swing.JLabel proxyPortLabel3;
    private javax.swing.JLabel proxyPortLabel4;
    private javax.swing.JTextField proxyPortText;
    private javax.swing.JTextField proxyPortText1;
    private javax.swing.JTextField proxyPortText2;
    private javax.swing.JTextField proxyPortText3;
    private javax.swing.JTextField proxyPortText4;
    private javax.swing.JScrollPane requestPane;
    private javax.swing.JScrollPane requestPane1;
    private javax.swing.JPanel requestPanel;
    private javax.swing.JPanel requestPanel1;
    private javax.swing.JComboBox<String> subAttackList;
    private javax.swing.JLabel subAttackTypeLabel;
    // End of variables declaration//GEN-END:variables
}
